---
- name: Get MAC addresses
  community.libvirt.virt:
    command: get_interfaces
    name: "{{ item }}"
  register: domain_info
  with_items: >-
    {{ (master.domain2address | map(attribute='hostname') | list)
       | union(worker.domain2address | map(attribute='hostname') | list) }}

- name: Set fact between domain name and MAC address
  ansible.builtin.set_fact:
    macs: "{{ macs | default({}) | combine({ (item.item + '_mac'): item.network_interfaces.interface_1.mac }) }}"
  with_items: "{{ domain_info['results'] }}"
  no_log: yes