name: release

on:
  push:
    paths:
      - 'release.txt'
    

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate tag and branchq
        run: |
          branch_name=$(cat $(find . -name "release.txt") | tail -1 | awk '{print $2"-"$3}')
          tag_name=$(cat $(find . -name "release.txt") | tail -1 | awk '{print $1"-"$3}')
          git branch $branch_name
          git tag $tag_name
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://saksons:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin $branch_name
          git push origin $tag_name