name: release

on:
  push:
    paths:
      - 'release.txt'
    

jobs:
  build:
    runs-on: ubuntu
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate coverage badge
        working-directory: ./app
        run: |
          git branch $(cat $(find . -name "release.txt") | tail -1 | awk '{print $2"-"$3}')
          git tag $(cat $(find . -name "release.txt") | tail -1 | awk '{print $1"-"$3}')
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://saksons:${{ secrets.GITHUBTOKEN }}@github.com/${{ github.repository }}
          git push origin 